[package]
name = "bento-network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bento-config = { workspace = true }
async-trait = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
